controller_server:
  ros__parameters:
    goal_checker_plugins: ["goal_checker"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 0.5
    controller_frequency: 5.0
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 10
      model_dt: 0.2
      batch_size: 1000
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.5
      vx_max: 0.5
      vx_min: -0.05
      vy_max: 0.20
      wz_max: 1.5
      ax_max: 0.25
      ax_min: -0.25
      ay_max: 0.25
      az_max: 3.0
      iteration_count: 1
      prune_distance: 2.0
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: false
      reset_period: 1.0 # (only in Humble)
      regenerate_noises: false
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      AckermannConstraints:
        min_turning_r: 0.2
      critics:
        - "ConstraintCritic"
        - "ObstaclesCritic"
        - "GoalCritic"
        - "GoalAngleCritic"
        - "PathAlignCritic"
        - "PathFollowCritic"
        - "PathAngleCritic"
        - "PreferForwardCritic"
        - "TwirlingCritic"
        - "VelocityDeadbandCritic"
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 2
        cost_weight: 10.0
        threshold_to_consider: 0.50
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.25
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 15.0
        threshold_to_consider: 0.50
      ObstaclesCritic:
        enabled: true
        cost_power: 2
        repulsion_weight: 1.5
        critical_weight: 20.0
        consider_footprint: true
        collision_cost: 10000.0
        collision_margin_distance: 0.2
        near_goal_distance: 0.5
        inflation_radius: 0.5 # (only in Humble)
        cost_scaling_factor: 3.0 # (only in Humble)
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 20.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 3
        threshold_to_consider: 0.50
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 40.0
        offset_from_furthest: 5
        threshold_to_consider: 0.5
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.25
        max_angle_to_furthest: 1.0
        mode: 0
      TwirlingCritic:
        enabled: true
        twirling_cost_power: 1
        twirling_cost_weight: 10.0
      VelocityDeadbandCritic:
        enabled: true
        cost_power: 1
        cost_weight: 35.0
        deadband_velocities: [0.1, 0.1, 0.6]
