controller_server:
  ros__parameters:
    controller_frequency: 5.0
    goal_checker_plugins: ["goal_checker"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 0.5
    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "nav2_mppi_controller::MPPIController"
      # shim controller params
      rotate_to_heading_angular_vel: 3.0
      max_angular_accel: 6.0
      # primary controller params
      time_steps: 10
      model_dt: 0.2
      batch_size: 1000
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.5
      vx_max: 1.0
      vx_min: -0.20
      vy_max: 0.15
      wz_max: 1.0
      ax_max: 0.5
      ax_min: -0.5
      ay_max: 0.5
      az_max: 1.5
      iteration_count: 3
      prune_distance: 2.0
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: false
      reset_period: 1.0 # (only in Humble)
      regenerate_noises: false
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      AckermannConstraints:
        min_turning_r: 0.2
      critics:
        - "ConstraintCritic"
        - "ObstaclesCritic"
        - "GoalCritic"
        - "GoalAngleCritic"
        - "PathAlignCritic"
        - "PathFollowCritic"
        - "PathAngleCritic"
        - "PreferForwardCritic"
        - "TwirlingCritic"
        - "VelocityDeadbandCritic"
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.0
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.25
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 15.0
        offset_from_furthest: 5
        threshold_to_consider: 1.0
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
        offset_from_furthest: 10
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0
      VelocityDeadbandCritic:
        enabled: true
        cost_power: 1
        cost_weight: 35.0
        deadband_velocities: [0.1, 0.1, 0.5]
      ObstaclesCritic:
        enabled: true
        cost_power: 1
        repulsion_weight: 20.0
        critical_weight: 160.0
        consider_footprint: true
        collision_cost: 10000.0
        collision_margin_distance: 0.2
        near_goal_distance: 0.5
        cost_scaling_factor: 1.0 # (only in Humble)
        inflation_radius: 1.5 # (only in Humble)
      TwirlingCritic:
        enabled: true
        twirling_cost_power: 1
        twirling_cost_weight: 10.0
