global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.25
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        max_obstacle_height: 0.5
        mark_threshold: 0
        observation_sources: scan rgbd
        scan:
          topic: /scan
          max_obstacle_height: 0.5
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 12.0
          raytrace_min_range: 0.0
          obstacle_max_range: 12.5
          obstacle_min_range: 0.2
        rgbd:
          topic: /camera/realsense2_camera_driver/depth/color/points
          min_obstacle_height: 0.10
          max_obstacle_height: 0.50
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 2.5
          raytrace_min_range: 0.3
          obstacle_max_range: 3.0
          obstacle_min_range: 0.3
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 30.0
        inflation_radius: 0.60
      always_send_full_costmap: false
