local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 9
      height: 9
      resolution: 0.025
      footprint: "[ [0.25, 0.16], [0.25, -0.16], [-0.2, -0.16], [-0.2, 0.16] ]"
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 30.0
        inflation_radius: 0.25
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.10
        z_voxels: 16
        max_obstacle_height: 0.5
        mark_threshold: 0
        observation_sources: scan rgbd
        scan:
          topic: /scan
          max_obstacle_height: 0.5
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 12.0
          raytrace_min_range: 0.0
          obstacle_max_range: 12.5
          obstacle_min_range: 0.0
        rgbd:
          topic: /camera/realsense2_camera_driver/depth/color/points
          min_obstacle_height: 0.03
          max_obstacle_height: 0.50
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 3.5
          raytrace_min_range: 0.0
          obstacle_max_range: 4.0
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True
