local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 2.0
      publish_frequency: 2.0
      global_frame: donatello/odom
      robot_base_frame: donatello/base_link
      rolling_window: true
      width: 4
      height: 4
      resolution: 0.05
      footprint: "[ [0.30, 0.16], [0.30, -0.16], [-0.20, -0.16], [-0.20, 0.16] ]"
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 30.0
        inflation_radius: 0.25
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        max_obstacle_height: 0.5
        mark_threshold: 0
        observation_sources: scan rgbd
        scan:
          topic: /scan
          max_obstacle_height: 0.5
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 12.0
          raytrace_min_range: 0.3
          obstacle_max_range: 12.5
          obstacle_min_range: 0.2
        rgbd:
          topic: /camera/realsense2_camera_driver/depth/color/points
          min_obstacle_height: 0.10
          max_obstacle_height: 0.50
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 2.5
          raytrace_min_range: 0.3
          obstacle_max_range: 3.0
          obstacle_min_range: 0.3
      always_send_full_costmap: false
