velocity_smoother:
  ros__parameters:
    smoothing_frequency: 40.0
    scale_velocities: True
    feedback: "OPEN_LOOP"
    max_velocity: [1.5, 1.5, 1.5]
    min_velocity: [-1.5, -1.5, -1.5]
    max_accel: [0.5, 0.5, 18.0]
    max_decel: [-3.0, -3.0, -18.0]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.01, 0.01, 0.05]
    velocity_timeout: 1.0
