velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: True
    feedback: "OPEN_LOOP"
    max_velocity: [1.5, 1.5, 1.5]
    min_velocity: [-1.5, -1.5, -1.5]
    max_accel: [0.5, 0.5, 1.5]
    max_decel: [-0.5, -0.5, -1.5]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.1, 0.1, 0.5]
    velocity_timeout: 1.0
