camera/realsense2_camera_driver:
  ros__parameters:
    device_type: 'd455'
    camera_name: 'camera'
    camera_namespace: 'camera'
    serial_no: ''
    usb_port_id: ''
    config_file: ''
    json_file_path: ''
    initial_reset: false
    accelerate_gpu_with_glsl: false
    rosbag_filename: ''
    log_level: 'info'
    output: 'screen'
    enable_color: true
    pointcloud:
      enable: true
      stream_filter: 2
      stream_index_filter: 0
      ordered_pc: false
      allow_no_texture_points: false
