camera/realsense2_camera_driver:
  ros__parameters:
    device_type: 'd435i'
    camera_name: 'camera'
    camera_namespace: 'camera'
    serial_no: ''
    usb_port_id: ''
    config_file: ''
    json_file_path: ''
    initial_reset: false
    accelerate_gpu_with_glsl: false
    rosbag_filename: ''
    log_level: 'info'
    output: 'screen'
    enable_color: true
    rgb_camera:
      color_profile: '0,0,0'
      color_format: 'RGB8'
      enable_auto_exposure: true
    enable_depth: true
    enable_infra: false
    enable_infra1: false
    enable_infra2: false
    depth_module:
      depth_profile: '0,0,0'
      depth_format: 'Z16'
      infra_profile: '0,0,0'
      infra_format: 'RGB8'
      infra1_format: 'Y8'
      infra2_format: 'Y8'
      exposure: 8500
      gain: 16
      hdr_enabled: false
      enable_auto_exposure: true
      exposure.1: 7500
      gain.1: 16
      exposure.2: 1
      gain.2: 16
    enable_sync: true
    enable_rgbd: true
    enable_gyro: true
    enable_accel: true
    gyro_fps: 0
    accel_fps: 0
    unite_imu_method: 0
    clip_distance: -2.
    angular_velocity_cov: 0.01
    linear_accel_cov: 0.01
    diagnostics_period: 0.0
    publish_tf: false # use static transforms in the URDF
    tf_publish_rate: 0.0
    pointcloud:
      enable: true
      stream_filter: 2
      stream_index_filter: 0
      ordered_pc: false
      allow_no_texture_points: false
    align_depth:
      enable: true
    colorizer:
      enable: false
    decimation_filter:
      enable: false
    spatial_filter:
      enable: false
    temporal_filter:
      enable: false
    disparity_filter:
      enable: false
    hole_filling_filter:
      enable: false
    hdr_merge:
      enable: false
    wait_for_device_timeout: -1.
    reconnect_timeout: 6.
