services:
  donatello-dev:
    build:
      context: ..
      dockerfile: docker/images/${ROSDISTRO:-humble}/Dockerfile
    container_name: donatello-dev
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    stdin_open: true
    tty: true
    user: ${USERID:-1000}:${GROUPID:-1000}
    privileged: ${PRIVILEGED_CONTAINER:-false}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /dev:/dev
      - ..:/home/developer/ws/src/project
      - donatello_persistence:/home/developer/ws/persistence
volumes:
  donatello_persistence:
