services:
  donatello-dev:
    build:
      context: ..
      dockerfile: docker/images/${ROSDISTRO:-humble}/Dockerfile
    container_name: donatello-dev
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    stdin_open: true
    tty: true
    user: ${USERID:-1000}:${GROUPID:-1000}
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /dev:/dev
      - ..:/home/developer/ws/src/project
      - donatello_persistence:/home/developer/ws/persistence
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    network_mode: host
    depends_on:
      - donatello-inorbit-agent
    pid: host
    ipc: host
  donatello-inorbit-agent:
    volumes:
      - donatello_inorbit_local:/root/.inorbit/local/
      - ../inorbit:/root/.inorbit/local
    image: inorbitai/agent:ros-humble-4.22.0
    network_mode: host
    pid: host # https://github.com/eProsima/Fast-DDS/issues/2956
    ipc: host
volumes:
  donatello_persistence:
  donatello_inorbit_local:
