cmd_vel_mux:
  ros__parameters:
    topics:
      navigation:
        topic: /cmd_vel_controller
        timeout: 0.5
        priority: 20
      joystick:
        topic: /cmd_vel_teleop
        timeout: 0.5
        priority: 10
