controller_server:
  ros__parameters:
    controller_frequency: 10.0
    progress_checker_plugins: ["progress_checker"] # progress_checker_plugin: "progress_checker" For Humble and older
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      # shim controller params
      max_angular_accel: 18.0 # leave the smoother handle this
      # primary controller params
      desired_linear_vel: 1.0
      use_velocity_scaled_lookahead_dist: true
      lookahead_dist: 0.5
      min_lookahead_dist: 0.5
      max_lookahead_dist: 1.5
      lookahead_time: 1.0
      use_rotate_to_heading: true
      rotate_to_heading_angular_vel: 1.0
      transform_tolerance: 0.1
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 0.25
      regulated_linear_scaling_min_radius: 1.5
      regulated_linear_scaling_min_speed: 0.25
      allow_reversing: false
      rotate_to_heading_min_angle: 0.8
      # max_robot_pose_search_dist: 10.0  # leave at default
