rosbridge_server:
  ros__parameters:
    port: 9090
    address: ""
    url_path: "/"
    retry_startup_delay: 5.0
    fragment_timeout: 600
    delay_between_messages: 0
    max_message_size: 10000000
    unregister_timeout: 10.0
    use_compression: false
    call_services_in_new_thread: true
    default_call_service_timeout: 5.0
    send_action_goals_in_new_thread: true
    topics_glob: ""
    services_glob: ""
    params_glob: ""
    bson_only_mode: false
